org: clouding

service: replead

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1

package: 
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws/sdk/*'

functions: ${file(src/lambdas/lambdas.yml):functions}

resources:
  Resources:
    LeadsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "LeadsTable"
        BillingMode: "PAY_PER_REQUEST"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"