org: clouding

service: replead

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  memorySize: 128
  environment:
    DYNAMO_LEADS_TABLE: !Ref LeadsTable
    GENERATE_REPORT_QUEUE_URL: !Ref GenerateReportQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource:
            - !GetAtt LeadsTable.Arn

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws/sdk/*"

functions: ${file(src/infra/lambdas/lambdas.yml):functions}

resources:
  Resources:
    LeadsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "LeadsTable"
        BillingMode: "PAY_PER_REQUEST"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"

    GenerateReportQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: GenerateReporQueue
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 180
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt GenerateReportQueueDLQ.Arn
          maxReceiveCount: 2

    GenerateReportQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: GenerateReportQueueDLQ
        MessageRetentionPeriod: 1209600 # 14 days
