org: clouding

service: replead

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  memorySize: 128
  environment:
    DYNAMO_LEADS_TABLE: !Ref LeadsTable
    GENERATE_REPORT_QUEUE_URL: !Ref GenerateReportQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource:
            - !GetAtt LeadsTable.Arn
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: !GetAtt GenerateReportQueue.Arn
package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws/sdk/*"

functions: ${file(src/infra/lambdas/lambdas.yml):functions}

resources:
  - ${file(./resources/dynamo/LeadsTable.yml)}
  - ${file(./resources/sqs/GenerateReportQueue.yml)}
  - ${file(./resources/s3/ReportsBucket.yml)}
