org: clouding

service: replead

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1

package: 
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws/sdk/*'

functions: ${file(src/lambdas/lambdas.yml):functions}